name: 'Run Pest Tests'
description: 'Run Pest tests with specific environment variables'
inputs:
  ENVIRONMENT:
    description: 'Environment name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Pest Tests - ${{ inputs.ENVIRONMENT }}
      run: vendor/bin/pest --ci
      shell: bash
      env:
        TABLEAU_URL: ${{ secrets.TABLEAU_URL }}
        TABLEAU_PRODUCT_VERSION: ${{ secrets.TABLEAU_PRODUCT_VERSION }}
        # Auth with PAT
        TABLEAU_PAT_NAME: ${{ secrets.TABLEAU_PAT_NAME }}
        TABLEAU_PAT_SECRET: ${{ secrets.TABLEAU_PAT_SECRET }}
        # Auth with Username
        TABLEAU_USERNAME: ${{ secrets.TABLEAU_USERNAME }}
        TABLEAU_PASSWORD: ${{ secrets.TABLEAU_PASSWORD }}
