name: 'Run Pest Tests'
description: 'Run Pest tests with specific environment variables'
inputs:
  ENVIRONMENT:
    description: 'Environment name'
    required: true
  TABLEAU_URL:
    description: 'Tableau URL'
    required: true
  TABLEAU_PRODUCT_VERSION:
    description: 'Tableau Product Version'
    required: true
  TABLEAU_PAT_NAME:
    description: 'Tableau PAT Name'
    required: true
  TABLEAU_PAT_SECRET:
    description: 'Tableau PAT Secret'
    required: true
  TABLEAU_USERNAME:
    description: 'Tableau Username'
    required: true
  TABLEAU_PASSWORD:
    description: 'Tableau Password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Pest Tests - ${{ inputs.ENVIRONMENT }}
      run: vendor/bin/pest --ci
      env:
        TABLEAU_URL: ${{ inputs.TABLEAU_URL }}
        TABLEAU_PRODUCT_VERSION: ${{ inputs.TABLEAU_PRODUCT_VERSION }}
        TABLEAU_PAT_NAME: ${{ inputs.TABLEAU_PAT_NAME }}
        TABLEAU_PAT_SECRET: ${{ inputs.TABLEAU_PAT_SECRET }}
        TABLEAU_USERNAME: ${{ inputs.TABLEAU_USERNAME }}
        TABLEAU_PASSWORD: ${{ inputs.TABLEAU_PASSWORD }}
